### PR TITLE
Featuress design button login and signup

### PR DESCRIPTION
**Pull request by Lakshyaraj-Singh**
added some css to buttons login and sign up

### CODE REVIEW

**Comment by Lakshyaraj-Singh** [comment]
Hi @dipu-s-repo68 Could you please add Hactober-accepted label
To my PR
Thankyou

**Comment by Lakshyaraj-Singh** [comment]
Screenshot_2024-10-11-13-54-42-40_40deb401b9ffe8e1df2f1cc5ba480b12
Screenshot_2024-10-11-13-54-52-76_40deb401b9ffe8e1df2f1cc5ba480b12

**Comment by dipu-s-repo68** [comment]
@Lakshyaraj-Singh please check you PR

**Comment by Lakshyaraj-Singh** [comment]
This was my first PR , so now can I just close the pull request or what? 
as the branch is merged
can you help!!!
thanks @dipu-s-repo68

**Comment by emergency000-lab** [comment]
@Lakshyaraj-Singh
You must delete the PR
Then again send PR

**Comment by dipu-s-repo68** [comment]
@Lakshyaraj-Singh done

**Comment by dipu-s-repo68** [comment]
@Lakshyaraj-Singh I'll close this PR

**Pull request merged**
